openapi: 3.1.0
info:
  title: AskUI Workspaces access-tokens runs API
  version: 0.2.15
tags:
- name: runs
paths:
  /api/v1/workspaces/{workspace_id}/runs:
    get:
      tags:
      - runs
      summary: List Runs
      operationId: list_runs_api_v1_workspaces__workspace_id__runs_get
      security:
      - Bearer: []
      - Basic: []
      parameters:
      - name: workspace_id
        in: path
        required: true
        schema:
          type: string
          format: uuid4
          title: Workspace Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListRunsResponseDto'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    RunnerAssignment:
      properties:
        ids:
          items:
            type: string
          type: array
          title: Ids
        host:
          $ref: '#/components/schemas/RunnerHost'
        tags:
          items:
            type: string
          type: array
          title: Tags
      type: object
      required:
      - host
      title: RunnerAssignment
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    RunStatus:
      type: string
      enum:
      - UPCOMING
      - PENDING
      - RUNNING
      - SKIPPED
      - SKIPPED_NOTHING_TO_RUN
      - PASSED_NOT_YET_REPORTED
      - FAILED_NOT_YET_REPORTED
      - PASSED
      - FAILED
      - CANCELED
      - SUSPENDED
      title: RunStatus
    RunResponseDto:
      properties:
        version:
          type: string
          title: Version
        id:
          type: string
          title: Id
        created_at:
          type: string
          format: date-time
          title: Created At
        name:
          type: string
          title: Name
        status:
          $ref: '#/components/schemas/RunStatus'
          default: UPCOMING
        to_be_started_at:
          type: string
          format: date-time
          title: To Be Started At
        started_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Started At
        schedule_id:
          type: string
          title: Schedule Id
        template:
          $ref: '#/components/schemas/RunTemplate'
        ended_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Ended At
        'no':
          type: integer
          title: 'No'
        schedule:
          $ref: '#/components/schemas/ScheduleReponseDto'
      type: object
      required:
      - name
      - to_be_started_at
      - schedule_id
      - template
      - 'no'
      - schedule
      title: RunResponseDto
    RunnerHost:
      type: string
      enum:
      - SELF
      - ASKUI
      title: RunnerHost
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ScheduleReponseDto:
      properties:
        version:
          type: string
          title: Version
        id:
          type: string
          title: Id
        created_at:
          type: string
          format: date-time
          title: Created At
        name:
          type: string
          title: Name
        status:
          $ref: '#/components/schemas/ScheduleStatus'
          default: ACTIVE
        started_at:
          type: string
          format: date-time
          title: Started At
        ended_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Ended At
        schedule:
          anyOf:
          - type: string
          - type: 'null'
          title: Schedule
        ended_after:
          anyOf:
          - type: integer
          - type: 'null'
          title: Ended After
        run_template:
          $ref: '#/components/schemas/RunTemplate'
        runs_count:
          type: integer
          title: Runs Count
          default: 0
        next_run_to_be_started_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Next Run To Be Started At
      type: object
      required:
      - name
      - started_at
      - run_template
      title: ScheduleReponseDto
    ScheduleStatus:
      type: string
      enum:
      - ACTIVE
      - SUSPENDED
      - ENDED
      title: ScheduleStatus
    ListRunsResponseDto:
      properties:
        data:
          items:
            $ref: '#/components/schemas/RunResponseDto'
          type: array
          title: Data
      type: object
      required:
      - data
      title: ListRunsResponseDto
    RunTemplate:
      properties:
        workspace_id:
          type: string
          title: Workspace Id
        workflows:
          anyOf:
          - items:
              type: string
            type: array
          - type: 'null'
          title: Workflows
        runner_assignment:
          $ref: '#/components/schemas/RunnerAssignment'
        data:
          additionalProperties: true
          type: object
          title: Data
      type: object
      required:
      - workspace_id
      - runner_assignment
      title: RunTemplate
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
    Basic:
      type: apiKey
      in: header
      name: Authorization
