openapi: 3.1.0
info:
  title: AskUI Workspaces access-tokens auth API
  version: 0.2.15
tags:
- name: auth
paths:
  /api/v1/auth/verification-email:
    post:
      tags:
      - auth
      summary: Send Verification Email
      description: Creates a job to send a verification email (only for users that have not verified their email yet) whose status can be retrieved using the `GET /auth/jobs/{job_id}` endpoint
      operationId: send_verification_email_api_v1_auth_verification_email_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendVerificationEmailCommand'
        required: true
      responses:
        '200':
          description: Email sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendVerificationEmailResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringErrorResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/auth/jobs/{job_id}:
    get:
      tags:
      - auth
      summary: Get Job Status
      operationId: get_job_status_api_v1_auth_jobs__job_id__get
      parameters:
      - name: job_id
        in: path
        required: true
        schema:
          type: string
          title: Job Id
      responses:
        '200':
          description: Job status retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetJobResponse'
        '404':
          description: Job not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringErrorResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringErrorResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    SendVerificationEmailResponse:
      properties:
        jobId:
          type: string
          title: Jobid
        jobStatus:
          type: string
          title: Jobstatus
      type: object
      required:
      - jobId
      - jobStatus
      title: SendVerificationEmailResponse
    SendVerificationEmailCommand:
      properties:
        email:
          type: string
          format: email
          title: Email
      type: object
      required:
      - email
      title: SendVerificationEmailCommand
    GetJobResponse:
      properties:
        id:
          type: string
          title: Id
        status:
          type: string
          title: Status
          description: The status of the job. Can be `pending`, `completed` etc.
      type: object
      required:
      - id
      - status
      title: GetJobResponse
    StringErrorResponse:
      properties:
        detail:
          type: string
          title: Detail
      type: object
      required:
      - detail
      title: StringErrorResponse
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
    Basic:
      type: apiKey
      in: header
      name: Authorization
